<a href="https://colab.research.google.com/github/tn610582/ML/blob/master/ML_scalar_vector_matrix_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sys
import numpy as np

In [24]:
#define scalar
x = 10
x

10

In [25]:
#defin scalar
x = np.array((1,2,3))
x

array([1, 2, 3])

In [26]:
print ('Vector Dimensions: {}'.format(x.shape))
print ('Vector Size: {}'.format(x.size))

Vector Dimensions: (3,)
Vector Size: 3


In [27]:
#define a matrix
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
print ('Matrix Dimensions: {}'.format(x.shape))
print ('Matrix Size: {}'.format(x.size))

Matrix Dimensions: (3, 3)
Matrix Size: 9


In [29]:
#define a matrix of a given dimension
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
#define 3-D tensor
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
print ('Tensor Dimensions: {}'.format(x.shape))
print ('Tensor Size: {}'.format(x.size))

Tensor Dimensions: (3, 3, 3)
Tensor Size: 27


In [33]:
#indexing
A = np.ones((5,5), dtype = np.int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
#indexing starts at 0
A[0,1] = 2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
A[:,0] = 3
A

array([[3, 2, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1]])

In [37]:
A[0,:] = 4
A

array([[4, 4, 4, 4, 4],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1]])

In [38]:
A[:,:] = 5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [39]:
# for higher dimension, add an index
A = np.ones((5,5,5), dtype = np.int)
#assign first row a new value
A[:,0,0] = 6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [44]:
#matrix operation
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2), dtype = np.int)
A


matrix([[1, 2],
        [3, 4]])

In [45]:
B

array([[1, 1],
       [1, 1]])

In [46]:
#element wise subtraction
C = A-B
C

matrix([[0, 1],
        [2, 3]])

In [47]:
# matrix multiplication
C = A*B
C

matrix([[3, 3],
        [7, 7]])

In [49]:
# matrix transpose
A = np.array(range(9))
A = A.reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [52]:
C = B.T
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
# tensors
A = np.ones((3,3,3,3,3,3,3,3,3,3))

print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
